#region Component Description
/*
Component: wsp_Ro08_KUKA Post Processor
Nickname: kuka_post
Category: WASPer_3DP
SubCategory: 5.1_Robot Gcode

Creates a native Robots IPostProcessor for KUKA systems. Connect its output to
the optional Post Processor (Ps) input of Robots Load Robot System before using
Create Program.

The postprocessor delegates target formatting and command handling to the native
Robots 2.2.5 KRL writer, then applies a WASPer/KUKA profile:
  - KSS template header and standard INI folds
  - configurable PTP speed, $ADVANCE, and $APO.CPTP
  - explicit $IPO_MODE = #BASE for a flange-mounted tool
  - KUKA|prc-compatible initial frame activation without forcing LOAD_DATA
  - optional explicit start-axis fold
  - Speed/Zone REAL attributes inlined numerically into KRL

It does not change target order, kinematics, process-command placement, or the
simulation represented by the Robots Program. An optional start-axis fold adds
a real PTP movement outside the simulated target sequence and must therefore be
used deliberately.
*/
#endregion

using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Reflection;
using System.Text.RegularExpressions;

using Grasshopper.Kernel;

using Robots;

namespace WASPer_3DP.Components._5_1_Robot_Gcode
{
    public sealed class wsp_Ro08_KUKA_Post_Processor : GH_Component
    {
        private readonly string _versionTag;

        public wsp_Ro08_KUKA_Post_Processor()
            : base(
                "wsp_Ro08_KUKA Post Processor",
                "kuka_post",
                "Creates a native Robots KUKA postprocessor with KSS-style initialization, " +
                "configurable motion settings, and numeric Speed/Zone values. Connect the " +
                "output to Load Robot System's optional Post Processor (Ps) input.",
                global::WASPer_3DP.WASPerPalette.DesignFabrication,
                "5.1_Robot Gcode")
        {
            Version version = Assembly.GetExecutingAssembly().GetName().Version;
            _versionTag = version != null
                ? $"v{version.Major}.{version.Minor}.{version.Build}"
                : "v1.0.x";
            Message = _versionTag;
        }

        public override Guid ComponentGuid =>
            new Guid("B827CC53-87C8-419E-973D-458E22620C04");

        public override GH_Exposure Exposure => GH_Exposure.primary;

        protected override System.Drawing.Bitmap Icon
        {
            get
            {
                try
                {
                    Assembly assembly = Assembly.GetExecutingAssembly();
                    using (var stream = assembly.GetManifestResourceStream(
                        "WASPer_3DP.Resources.Icons.wsp_Ro08_KUKA Post Processor.png"))
                    {
                        return stream != null ? new System.Drawing.Bitmap(stream) : null;
                    }
                }
                catch
                {
                    return null;
                }
            }
        }

        protected override void RegisterInputParams(GH_InputParamManager p)
        {
            p.AddNumberParameter(
                "ptp_speed", "ptp_speed",
                "Initial KUKA PTP speed in percent, used by BAS(#PTP_PARAMS,...). " +
                "Target-specific PTP speed changes generated by Robots remain active.",
                GH_ParamAccess.item,
                15.0);

            p.AddIntegerParameter(
                "advance", "advance",
                "KUKA advance-run look-ahead count assigned to $ADVANCE. KUKA|prc commonly " +
                "uses 3. Valid range: 0 to 5.",
                GH_ParamAccess.item,
                3);

            p.AddNumberParameter(
                "c_ptp", "c_ptp",
                "Initial KUKA PTP approximation value assigned to $APO.CPTP, in percent. " +
                "Valid range: 0 to 100.",
                GH_ParamAccess.item,
                100.0);

            p.AddNumberParameter(
                "start_joints", "start_joints",
                "Optional list of exactly six KUKA start-axis values [A1,A2,A3,A4,A5,A6] " +
                "in degrees. When supplied, Ro08 inserts a real STARTPOSITION PTP before " +
                "the Robots target sequence. This extra move is not represented in Program " +
                "Simulation. Leave disconnected to keep code and simulation synchronized.",
                GH_ParamAccess.list);
            p[3].Optional = true;
        }

        protected override void RegisterOutputParams(GH_OutputParamManager p)
        {
            p.AddGenericParameter(
                "post_processor", "post",
                "Native Robots KUKA postprocessor. Connect to the optional Ps input of " +
                "Load Robot System, then use that Robot System in Create Program.",
                GH_ParamAccess.item);
        }

        protected override void SolveInstance(IGH_DataAccess DA)
        {
            Message = _versionTag;

            double ptpSpeed = 15.0;
            int advance = 3;
            double cPtp = 100.0;
            var startJoints = new List<double>();

            DA.GetData(0, ref ptpSpeed);
            DA.GetData(1, ref advance);
            DA.GetData(2, ref cPtp);
            bool hasStart = DA.GetDataList(3, startJoints) && startJoints.Count > 0;

            if (!IsFinite(ptpSpeed) || ptpSpeed < 0.0 || ptpSpeed > 100.0)
            {
                AddRuntimeMessage(
                    GH_RuntimeMessageLevel.Error,
                    "'ptp_speed' must be a finite percentage between 0 and 100.");
                return;
            }

            if (advance < 0 || advance > 5)
            {
                AddRuntimeMessage(
                    GH_RuntimeMessageLevel.Error,
                    "'advance' must be an integer between 0 and 5.");
                return;
            }

            if (!IsFinite(cPtp) || cPtp < 0.0 || cPtp > 100.0)
            {
                AddRuntimeMessage(
                    GH_RuntimeMessageLevel.Error,
                    "'c_ptp' must be a finite percentage between 0 and 100.");
                return;
            }

            double[] start = null;
            if (hasStart)
            {
                if (startJoints.Count != 6 || startJoints.Any(value => !IsFinite(value)))
                {
                    AddRuntimeMessage(
                        GH_RuntimeMessageLevel.Error,
                        "'start_joints' must contain exactly six finite values in degrees, " +
                        "ordered A1 through A6.");
                    return;
                }

                start = startJoints.ToArray();
            }

            try
            {
                // Keep the socket generic so Grasshopper can discover this component
                // without resolving the separate Robots.Grasshopper UI assembly.
                // Robots GH_PostProcessor accepts the raw IPostProcessor on connection.
                DA.SetData(0, new WasperKukaPostProcessor(
                    ptpSpeed, advance, cPtp, start));
            }
            catch (Exception ex)
            {
                AddRuntimeMessage(
                    GH_RuntimeMessageLevel.Error,
                    "Could not create the KUKA postprocessor: " + ex.Message);
                return;
            }

            string message =
                $"KUKA postprocessor ready: PTP {Fmt(ptpSpeed)}%, " +
                $"$ADVANCE={advance}, $APO.CPTP={Fmt(cPtp)}.";
            if (hasStart)
            {
                message +=
                    " STARTPOSITION is enabled and adds a PTP move that is not included " +
                    "in Robots Program Simulation.";
            }

            AddRuntimeMessage(GH_RuntimeMessageLevel.Remark, message);
        }

        private static bool IsFinite(double value) =>
            !double.IsNaN(value) && !double.IsInfinity(value);

        private static string Fmt(double value) =>
            value.ToString("0.###", CultureInfo.InvariantCulture);
    }

    internal sealed class WasperKukaPostProcessor : IPostProcessor
    {
        private static readonly Regex RealDeclarationRegex = new Regex(
            @"^\s*DECL\s+GLOBAL\s+REAL\s+([A-Za-z][A-Za-z0-9_]*)\s*=\s*(.+?)\s*$",
            RegexOptions.Compiled | RegexOptions.CultureInvariant |
            RegexOptions.IgnoreCase);

        private readonly double _ptpSpeed;
        private readonly int _advance;
        private readonly double _cPtp;
        private readonly double[] _startJoints;

        public WasperKukaPostProcessor(
            double ptpSpeed,
            int advance,
            double cPtp,
            double[] startJoints)
        {
            _ptpSpeed = ptpSpeed;
            _advance = advance;
            _cPtp = cPtp;
            _startJoints = startJoints == null
                ? null
                : (double[])startJoints.Clone();
        }

        public List<List<List<string>>> GetCode(
            RobotSystem system,
            Robots.Program program)
        {
            if (system == null) throw new ArgumentNullException(nameof(system));
            if (program == null) throw new ArgumentNullException(nameof(program));
            if (system.Manufacturer != Manufacturers.KUKA)
            {
                throw new InvalidOperationException(
                    "The WASPer KUKA postprocessor can only be used with a KUKA Robot System.");
            }

            IPostProcessor native = CreateNativeKrlPostProcessor();
            List<List<List<string>>> code = native.GetCode(system, program);
            NormalizeCodeLines(code);

            for (int group = 0; group < code.Count; group++)
            {
                List<List<string>> groupCode = code[group];
                if (groupCode == null || groupCode.Count < 2)
                {
                    throw new InvalidOperationException(
                        "Robots returned an unexpected KUKA code tree. Expected Main and DAT files.");
                }

                InlineSpeedAndZoneAttributes(groupCode);
                groupCode[0] = TransformMainFile(
                    groupCode[0],
                    program,
                    group);
            }

            return code;
        }

        private static void NormalizeCodeLines(
            List<List<List<string>>> code)
        {
            if (code == null) return;

            string[] separators = { "\r\n", "\n", "\r" };
            foreach (List<List<string>> group in code)
            {
                if (group == null) continue;

                foreach (List<string> file in group)
                {
                    if (file == null) continue;

                    for (int i = 0; i < file.Count; i++)
                    {
                        string item = file[i] ?? string.Empty;
                        if (item.IndexOf('\r') < 0 && item.IndexOf('\n') < 0)
                            continue;

                        string[] lines = item.Split(
                            separators,
                            StringSplitOptions.None);
                        file.RemoveAt(i);
                        file.InsertRange(i, lines);
                        i += lines.Length - 1;
                    }
                }
            }
        }

        private static IPostProcessor CreateNativeKrlPostProcessor()
        {
            Assembly robotsAssembly = typeof(RobotSystem).Assembly;
            Type type = robotsAssembly.GetType(
                "Robots.KRLPostProcessor",
                throwOnError: false,
                ignoreCase: false);
            if (type == null || !typeof(IPostProcessor).IsAssignableFrom(type))
            {
                throw new InvalidOperationException(
                    "The native Robots KRL postprocessor could not be found. " +
                    "Ro08 currently targets Robots.Rhino 2.2.5.");
            }

            object instance = Activator.CreateInstance(type, nonPublic: true);
            if (!(instance is IPostProcessor postProcessor))
            {
                throw new InvalidOperationException(
                    "The native Robots KRL postprocessor could not be instantiated.");
            }

            return postProcessor;
        }

        private static void InlineSpeedAndZoneAttributes(
            List<List<string>> groupCode)
        {
            List<string> dat = groupCode[1];
            var replacements = new Dictionary<string, string>(
                StringComparer.OrdinalIgnoreCase);

            for (int i = dat.Count - 1; i >= 0; i--)
            {
                Match match = RealDeclarationRegex.Match(dat[i] ?? string.Empty);
                if (!match.Success) continue;

                string name = match.Groups[1].Value;
                if (!name.StartsWith("Speed", StringComparison.OrdinalIgnoreCase) &&
                    !name.StartsWith("Zone", StringComparison.OrdinalIgnoreCase))
                {
                    continue;
                }

                replacements[name] = match.Groups[2].Value.Trim();
                dat.RemoveAt(i);
            }

            if (replacements.Count == 0) return;

            foreach (List<string> file in groupCode)
            {
                for (int i = 0; i < file.Count; i++)
                {
                    string line = file[i] ?? string.Empty;
                    foreach (KeyValuePair<string, string> replacement in replacements)
                    {
                        line = Regex.Replace(
                            line,
                            $@"\b{Regex.Escape(replacement.Key)}\b",
                            replacement.Value,
                            RegexOptions.CultureInvariant |
                            RegexOptions.IgnoreCase);
                    }
                    file[i] = line;
                }
            }
        }

        private List<string> TransformMainFile(
            List<string> source,
            Robots.Program program,
            int group)
        {
            if (source == null)
                throw new ArgumentNullException(nameof(source));

            int definition = FindLine(source, line =>
                line.TrimStart().StartsWith("DEF ", StringComparison.OrdinalIgnoreCase));
            int end = FindLastLine(source, line =>
                string.Equals(line.Trim(), "END", StringComparison.OrdinalIgnoreCase));

            if (definition < 0 || end <= definition)
            {
                throw new InvalidOperationException(
                    "The native Robots KUKA main file has no valid DEF/END module.");
            }

            string defLine = source[definition].TrimEnd();
            var preserved = new List<string>();
            bool beforeProgramStart = true;
            for (int i = definition + 1; i < end; i++)
            {
                string line = source[i] ?? string.Empty;
                string compact = RemoveWhitespace(line);

                if (string.Equals(
                        compact,
                        ";STARTPROG",
                        StringComparison.OrdinalIgnoreCase))
                {
                    beforeProgramStart = false;
                }

                if (string.Equals(
                        compact,
                        "BAS(#INITMOV,0)",
                        StringComparison.OrdinalIgnoreCase) ||
                    compact.StartsWith("$ADVANCE=", StringComparison.OrdinalIgnoreCase) ||
                    compact.StartsWith("$APO.CPTP=", StringComparison.OrdinalIgnoreCase) ||
                    (beforeProgramStart &&
                     compact.StartsWith("$LOAD=", StringComparison.OrdinalIgnoreCase)))
                {
                    continue;
                }

                preserved.Add(line);
            }

            bool hasIpoMode = preserved.Any(line =>
                RemoveWhitespace(line).StartsWith(
                    "$IPO_MODE=",
                    StringComparison.OrdinalIgnoreCase));

            if (!hasIpoMode)
            {
                int frameActivation = preserved.FindIndex(line =>
                {
                    string compact = RemoveWhitespace(line);
                    return compact.StartsWith("$TOOL=", StringComparison.OrdinalIgnoreCase) ||
                           compact.StartsWith("$BASE=", StringComparison.OrdinalIgnoreCase);
                });

                preserved.Insert(
                    frameActivation >= 0 ? frameActivation : 0,
                    "$IPO_MODE = #BASE");
            }

            var result = new List<string>
            {
                "&ACCESS RVP",
                "&REL 1",
                @"&PARAM TEMPLATE = C:\KRC\Roboter\Template\vorgabe",
                "&PARAM EDITMASK = *",
                defLine,
                string.Empty,
                ";FOLD INI",
                ";FOLD BASISTECH INI",
                "GLOBAL INTERRUPT DECL 3 WHEN $STOPMESS==TRUE DO IR_STOPM ( )",
                "INTERRUPT ON 3",
                "BAS (#INITMOV,0 )",
                ";ENDFOLD (BASISTECH INI)",
                ";ENDFOLD (INI)",
                string.Empty
            };

            if (_startJoints != null)
            {
                AddStartPosition(result, program, group);
                result.Add(string.Empty);
            }

            result.Add(
                $";FOLD WASPER MOTION SETTINGS - PTP SPEED IS {Fmt(_ptpSpeed)}%, " +
                $"ADVANCE IS {_advance}");
            result.Add($"BAS (#PTP_PARAMS,{Fmt(_ptpSpeed)})");
            result.Add($"$ADVANCE={_advance}");
            result.Add($"$APO.CPTP={Fmt(_cPtp)}");
            result.Add(";ENDFOLD");
            result.Add(string.Empty);
            result.AddRange(preserved);
            result.Add("END");

            return result;
        }

        private void AddStartPosition(
            IList<string> code,
            Robots.Program program,
            int group)
        {
            Target firstTarget = null;
            if (program.Targets.Count > 0 &&
                group >= 0 &&
                group < program.Targets[0].ProgramTargets.Count)
            {
                firstTarget = program.Targets[0].ProgramTargets[group].Target;
            }

            int? toolNumber = firstTarget?.Tool?.Number;
            int? baseNumber = firstTarget?.Frame?.Number;

            string toolText = toolNumber.HasValue
                ? toolNumber.Value.ToString(CultureInfo.InvariantCulture)
                : "UNSET";
            string baseText = baseNumber.HasValue
                ? baseNumber.Value.ToString(CultureInfo.InvariantCulture)
                : "UNSET";

            code.Add(
                $";FOLD STARTPOSITION - BASE IS {baseText}, TOOL IS {toolText}, " +
                $"SPEED IS {Fmt(_ptpSpeed)}%");
            code.Add("$BWDSTART = FALSE");
            code.Add($"PDAT_ACT = {{VEL {Fmt(_ptpSpeed)},ACC 100,APO_DIST 50}}");

            if (toolNumber.HasValue && baseNumber.HasValue)
            {
                code.Add(
                    $"FDAT_ACT = {{TOOL_NO {toolNumber.Value},BASE_NO " +
                    $"{baseNumber.Value},IPO_FRAME #BASE}}");
            }
            else
            {
                code.Add(
                    "; Controller TOOL_NO/BASE_NO unavailable on the first target; " +
                    "use Ro06/Ro07 to assign numbered controller data.");
            }

            code.Add($"BAS (#PTP_PARAMS,{Fmt(_ptpSpeed)})");
            code.Add(
                "PTP {" +
                string.Join(
                    ",",
                    _startJoints.Select(
                        (value, index) => $"A{index + 1} {Fmt(value)}")) +
                ",E1 0,E2 0,E3 0,E4 0}");
            code.Add(";ENDFOLD");
        }

        private static int FindLine(
            IList<string> lines,
            Func<string, bool> predicate)
        {
            for (int i = 0; i < lines.Count; i++)
            {
                if (predicate(lines[i] ?? string.Empty)) return i;
            }
            return -1;
        }

        private static int FindLastLine(
            IList<string> lines,
            Func<string, bool> predicate)
        {
            for (int i = lines.Count - 1; i >= 0; i--)
            {
                if (predicate(lines[i] ?? string.Empty)) return i;
            }
            return -1;
        }

        private static string RemoveWhitespace(string value) =>
            new string((value ?? string.Empty).Where(c => !char.IsWhiteSpace(c)).ToArray());

        private static string Fmt(double value) =>
            value.ToString("0.###", CultureInfo.InvariantCulture);
    }
}
