#region Component Description
/*
Component: wsp_Gp06_Assign BCs to Points (Thermal Solver)
Category: WASPerformance / 6_Grids of points

Purpose
    N-boundary generalization of wsp_Gp05_Assign BC to Points (Thermal Solver). Instead of two
    fixed bc_1_geo/bc_2_geo item inputs, this component takes a single ordered LIST of reference
    geometries (bcs_geo) and produces one output tree branch per list item, so any number of
    boundary conditions can be assigned in one component.

    Point-selection logic per BC geometry is unchanged from Gp05: closed volumes (Mesh/Brep/
    Box/Extrusion/BoundingBox) select grid points inside or on the volume; open geometry (open
    Mesh/Brep/Surface/Curve/Point) selects the closest grid points plus a local covering band so
    coarse grids still get boundary coverage.

    Intersections between BC geometries are resolved by LIST ORDER: if two or more bcs_geo items
    claim the same grid point, that point is kept only by whichever item comes first (lowest
    index) and is removed from every later item. This mirrors the bc1-wins-over-bc2 priority rule
    from Gp05, generalized to N items.

Inputs
    grid : List<Point3d>
        Grid points generated by Gp01/Gp02/Gp03/Gp04, usually the untrimmed_grid output. Every
        BC branch is assigned from this same list.

    bcs_geo : List<Geometry>
        One geometry per boundary condition, in priority order. Item 0 becomes branch {0} of
        bcs_pts, item 1 becomes branch {1}, and so on; there is no fixed limit on the number of
        items. Closed Mesh/Brep/Box/Extrusion/BoundingBox volumes select points inside or on the
        volume; open Mesh/Brep/Surface/Curve/Point geometries select the closest covering grid
        points. When geometries overlap on the same grid point, the earlier (lower-index) item
        wins and the point is removed from every later item.

Outputs
    bcs_pts : DataTree<Point3d>
        Grid points assigned to each boundary condition, one branch per bcs_geo item at the
        matching index (branch {i} <-> bcs_geo item i). Contested points end up only in the
        branch of the first BC that claims them.

    summary : List<string>
        One line per BC (index, interpreted geometry type, resulting point count, points lost to
        an earlier BC), plus a final line reporting grid points left unassigned to any BC.
*/
#endregion

using System;
using System.Collections.Generic;
using System.Linq;

using Rhino;
using Rhino.Geometry;

using Grasshopper.Kernel;
using Grasshopper.Kernel.Data;
using Grasshopper.Kernel.Types;

namespace WASPer_3DP.Components._6_Grids_of_points
{
    public class wsp_Gp06_AssignBCsToPointsThermalSolver : GH_Component
    {
        private readonly string _versionTag;

        public wsp_Gp06_AssignBCsToPointsThermalSolver()
            : base(
                "wsp_Gp06_Assign BCs to Points (Thermal Solver)",
                "Assign BCs Pts",
                "Assigns thermal solver boundary-condition point sets, one tree branch per bcs_geo item, from an unlimited ordered list of closed or open reference geometry. Overlaps between BC geometries are resolved by list order: earlier items win.",
                global::WASPer_3DP.WASPerPalette.Performance,
                "6_Grids of points")
        {
            var asm = System.Reflection.Assembly.GetExecutingAssembly();
            var v = asm.GetName().Version;
            _versionTag = v != null ? $"v{v.Major}.{v.Minor}.{v.Build}" : "v1.0.x";
            Message = _versionTag;
        }

        public override Guid ComponentGuid
        {
            get { return new Guid("3E7D9F2A-8B4C-4A1E-9D6F-5C2A8E1B4F9D"); }
        }

        protected override System.Drawing.Bitmap Icon
        {
            get
            {
                try
                {
                    var assembly = System.Reflection.Assembly.GetExecutingAssembly();
                    using (var stream = assembly.GetManifestResourceStream("WASPer_3DP.Resources.Icons.wsp_Gp06_Assign BCs to Points (Thermal Solver).png"))
                        return stream != null ? new System.Drawing.Bitmap(stream) : null;
                }
                catch { }
                return null;
            }
        }

        protected override void RegisterInputParams(GH_InputParamManager pManager)
        {
            pManager.AddPointParameter(
                "grid",
                "grid",
                "Grid points from Gp01/Gp02/Gp03/Gp04, usually the untrimmed_grid output. Every BC branch is assigned from this same list.",
                GH_ParamAccess.list);

            pManager.AddGenericParameter(
                "bcs_geo",
                "bcs_geo",
                "One geometry per boundary condition, in priority order. Item 0 becomes branch {0} of bcs_pts, item 1 becomes branch {1}, and so on -- add as many items as needed, there is no fixed limit. Closed Mesh/Brep/Box/Extrusion/BoundingBox volumes select grid points inside or on the volume; open Mesh/Brep/Surface/Curve/Point geometries select the closest grid points plus a local covering band so coarse grids still get boundary coverage. When two or more items claim the same grid point, that point is kept only by whichever item appears first (lowest index) in this list and is removed from every later item -- this is how overlapping/conflicting BC geometry is resolved.",
                GH_ParamAccess.list);
            pManager[1].Optional = true;
        }

        protected override void RegisterOutputParams(GH_OutputParamManager pManager)
        {
            pManager.AddPointParameter(
                "bcs_pts",
                "bcs_pts",
                "Grid points assigned to each boundary condition, as a tree with one branch per bcs_geo item at the matching index: branch {i} holds the points claimed by bcs_geo item i. A point contested by more than one BC ends up only in the branch of the first (lowest-index) BC that claims it; every branch index from 0 to bcs_geo.Count-1 is present even if empty.",
                GH_ParamAccess.tree);

            pManager.AddTextParameter(
                "summary",
                "summary",
                "One line per boundary condition, in the same order as bcs_geo: index, interpreted geometry type, resulting point count, and how many contested points were lost to an earlier BC. A final line reports how many grid points were left unassigned to any BC (adiabatic / uncovered nodes).",
                GH_ParamAccess.list);
        }

        protected override void SolveInstance(IGH_DataAccess DA)
        {
            Message = _versionTag;

            var grid = new List<Point3d>();
            if (!DA.GetDataList(0, grid)) return;
            CompactValidPoints(grid);

            var tree = new GH_Structure<GH_Point>();
            var summary = new List<string>();

            if (grid.Count == 0)
            {
                AddRuntimeMessage(GH_RuntimeMessageLevel.Warning, "Provide at least one grid point.");
                DA.SetDataTree(0, tree);
                summary.Add("No grid points supplied.");
                DA.SetDataList(1, summary);
                return;
            }

            var bcsRaw = new List<object>();
            DA.GetDataList(1, bcsRaw);

            if (bcsRaw == null || bcsRaw.Count == 0)
            {
                AddRuntimeMessage(GH_RuntimeMessageLevel.Warning, "Provide at least one bcs_geo item.");
                DA.SetDataTree(0, tree);
                summary.Add("No bcs_geo items supplied.");
                DA.SetDataList(1, summary);
                return;
            }

            double tol = RhinoDoc.ActiveDoc == null ? 0.01 : RhinoDoc.ActiveDoc.ModelAbsoluteTolerance;
            GridMetrics metrics = GridMetrics.FromPoints(grid, tol);

            var references = new List<BoundaryReference>(bcsRaw.Count);
            foreach (object raw in bcsRaw)
                references.Add(BoundaryReference.FromObject(raw, tol));

            // Any BC that carries open geometry needs the shared point index. Building it once
            // avoids duplicating the largest temporary structure across every BC pass.
            bool anyOpen = references.Any(r => r.HasOpenGeometry);
            RTree pointTree = anyOpen ? BuildPointTree(grid) : null;

            var claimed = new HashSet<int>();

            for (int i = 0; i < references.Count; i++)
            {
                BoundaryReference reference = references[i];
                object rawItem = bcsRaw[i];

                if (rawItem != null && reference.IsEmpty)
                    AddRuntimeMessage(GH_RuntimeMessageLevel.Warning, $"bcs_geo[{i}] could not be interpreted. Use Box, Mesh, Brep, Surface, Extrusion, Curve, or Point.");

                HashSet<int> matched = AssignBoundaryIndices(grid, reference, metrics, tol, pointTree);
                int matchedBeforePriority = matched.Count;

                int lostToEarlier = 0;
                foreach (int idx in matched)
                {
                    if (claimed.Contains(idx)) lostToEarlier++;
                }
                matched.ExceptWith(claimed);
                claimed.UnionWith(matched);

                var path = new GH_Path(i);
                tree.EnsurePath(path);
                List<Point3d> pts = IndicesToPoints(grid, matched);
                foreach (Point3d p in pts)
                    tree.Append(new GH_Point(p), path);

                if (rawItem != null && !reference.IsEmpty)
                {
                    if (matchedBeforePriority == 0)
                        AddRuntimeMessage(GH_RuntimeMessageLevel.Warning, $"bcs_geo[{i}] did not find any grid points.");
                    else if (pts.Count == 0)
                        AddRuntimeMessage(GH_RuntimeMessageLevel.Warning, $"bcs_geo[{i}]: every matching grid point was already claimed by an earlier BC.");
                }

                string typeLabel = rawItem == null ? "unwired" : reference.DescribeKind();
                string line = $"BC[{i}] ({typeLabel}): {pts.Count} point(s).";
                if (lostToEarlier > 0)
                    line += $" {lostToEarlier} contested point(s) kept by an earlier BC.";
                summary.Add(line);
            }

            int unassigned = grid.Count - claimed.Count;
            summary.Add($"{unassigned} grid point(s) left unassigned to any BC (adiabatic).");

            DA.SetDataTree(0, tree);
            DA.SetDataList(1, summary);
        }

        private static void CompactValidPoints(List<Point3d> points)
        {
            int write = 0;
            for (int read = 0; read < points.Count; read++)
            {
                Point3d point = points[read];
                if (!point.IsValid) continue;
                points[write++] = point;
            }

            if (write < points.Count)
                points.RemoveRange(write, points.Count - write);
        }

        private static HashSet<int> AssignBoundaryIndices(
            List<Point3d> grid,
            BoundaryReference reference,
            GridMetrics metrics,
            double tol,
            RTree pointTree)
        {
            var result = new HashSet<int>();
            if (reference == null || reference.IsEmpty || grid == null || grid.Count == 0)
                return result;

            double surfaceTol = Math.Max(tol * 2.0, metrics.MinSpacing * 0.02);
            double bandRadius = Math.Max(metrics.HalfDiagonal + surfaceTol, tol * 10.0);

            for (int i = 0; i < grid.Count; i++)
            {
                Point3d pt = grid[i];

                if (reference.ContainsClosed(pt, tol, surfaceTol))
                {
                    result.Add(i);
                    continue;
                }

                if (reference.IsCloseToOpen(pt, bandRadius))
                    result.Add(i);
            }

            if (reference.HasOpenGeometry)
            {
                var samples = reference.SampleOpenGeometry(Math.Max(metrics.MinSpacing, tol * 10.0));
                double startRadius = Math.Max(metrics.HalfDiagonal + surfaceTol, metrics.MinSpacing);
                double maxRadius = Math.Max(metrics.BoxDiagonal, startRadius);

                foreach (Point3d sample in samples)
                {
                    int nearest = FindNearestIndex(pointTree, grid, sample, startRadius, maxRadius);
                    if (nearest >= 0) result.Add(nearest);
                }
            }

            return result;
        }

        private static List<Point3d> IndicesToPoints(List<Point3d> grid, HashSet<int> indices)
        {
            var sorted = indices.ToList();
            sorted.Sort();

            var result = new List<Point3d>(sorted.Count);
            foreach (int i in sorted)
            {
                if (i >= 0 && i < grid.Count) result.Add(grid[i]);
            }

            return result;
        }

        private static RTree BuildPointTree(List<Point3d> points)
        {
            var tree = new RTree();
            for (int i = 0; i < points.Count; i++)
                tree.Insert(points[i], i);
            return tree;
        }

        private static int FindNearestIndex(
            RTree tree,
            List<Point3d> points,
            Point3d sample,
            double startRadius,
            double maxRadius)
        {
            int best = -1;
            double bestD2 = double.PositiveInfinity;
            double radius = Math.Max(startRadius, RhinoMath.ZeroTolerance);
            double limit = Math.Max(maxRadius, radius);

            while (best < 0 && radius <= limit * 1.0001)
            {
                var sphere = new Sphere(sample, radius);
                tree.Search(sphere, (sender, args) =>
                {
                    int id = args.Id;
                    if (id < 0 || id >= points.Count) return;

                    double d2 = sample.DistanceToSquared(points[id]);
                    if (d2 < bestD2)
                    {
                        bestD2 = d2;
                        best = id;
                    }
                });

                if (best >= 0) break;
                radius *= 2.0;
            }

            if (best >= 0) return best;

            for (int i = 0; i < points.Count; i++)
            {
                double d2 = sample.DistanceToSquared(points[i]);
                if (d2 < bestD2)
                {
                    bestD2 = d2;
                    best = i;
                }
            }

            return best;
        }

        private sealed class BoundaryReference
        {
            private readonly List<Mesh> _closedMeshes = new List<Mesh>();
            private readonly List<Mesh> _openMeshes = new List<Mesh>();
            private readonly List<Brep> _closedBreps = new List<Brep>();
            private readonly List<Brep> _openBreps = new List<Brep>();
            private readonly List<Curve> _curves = new List<Curve>();
            private readonly List<Point3d> _points = new List<Point3d>();

            private readonly List<BoundingBox> _closedMeshBoxes = new List<BoundingBox>();
            private readonly List<BoundingBox> _openMeshBoxes = new List<BoundingBox>();
            private readonly List<BoundingBox> _closedBrepBoxes = new List<BoundingBox>();
            private readonly List<BoundingBox> _openBrepBoxes = new List<BoundingBox>();
            private readonly List<BoundingBox> _curveBoxes = new List<BoundingBox>();

            public bool IsEmpty
            {
                get
                {
                    return _closedMeshes.Count == 0 &&
                           _openMeshes.Count == 0 &&
                           _closedBreps.Count == 0 &&
                           _openBreps.Count == 0 &&
                           _curves.Count == 0 &&
                           _points.Count == 0;
                }
            }

            public bool HasOpenGeometry
            {
                get { return _openMeshes.Count > 0 || _openBreps.Count > 0 || _curves.Count > 0 || _points.Count > 0; }
            }

            public string DescribeKind()
            {
                if (_closedMeshes.Count > 0) return "closed mesh";
                if (_openMeshes.Count > 0) return "open mesh";
                if (_closedBreps.Count > 0) return "closed brep/solid";
                if (_openBreps.Count > 0) return "open brep/surface";
                if (_curves.Count > 0) return "curve";
                if (_points.Count > 0) return "point";
                return "unrecognized";
            }

            public static BoundaryReference FromObject(object raw, double tol)
            {
                var reference = new BoundaryReference();
                object value = Unwrap(raw);
                if (value == null) return reference;

                Mesh mesh = value as Mesh;
                if (mesh != null)
                {
                    Mesh m = mesh.DuplicateMesh();
                    if (m != null && m.IsValid)
                    {
                        if (m.IsClosed) reference.AddClosedMesh(m, tol);
                        else reference.AddOpenMesh(m, tol);
                    }
                    return reference;
                }

                Brep brep = value as Brep;
                if (brep != null)
                {
                    Brep b = brep.DuplicateBrep();
                    if (b != null && b.IsValid)
                    {
                        if (b.IsSolid) reference.AddClosedBrep(b, tol);
                        else reference.AddOpenBrep(b, tol);
                    }
                    return reference;
                }

                Surface surface = value as Surface;
                if (surface != null)
                {
                    Brep b = Brep.CreateFromSurface(surface);
                    if (b != null && b.IsValid) reference.AddOpenBrep(b, tol);
                    return reference;
                }

                Extrusion extrusion = value as Extrusion;
                if (extrusion != null)
                {
                    Brep b = extrusion.ToBrep();
                    if (b != null && b.IsValid)
                    {
                        if (b.IsSolid) reference.AddClosedBrep(b, tol);
                        else reference.AddOpenBrep(b, tol);
                    }
                    return reference;
                }

                Curve curve = value as Curve;
                if (curve != null)
                {
                    Curve c = curve.DuplicateCurve();
                    if (c != null && c.IsValid) reference.AddCurve(c, tol);
                    return reference;
                }

                if (value is Box)
                {
                    Box box = (Box)value;
                    Brep b = box.ToBrep();
                    if (b != null && b.IsValid) reference.AddClosedBrep(b, tol);
                    return reference;
                }

                if (value is BoundingBox)
                {
                    BoundingBox bb = (BoundingBox)value;
                    if (bb.IsValid)
                    {
                        Brep b = new Box(bb).ToBrep();
                        if (b != null && b.IsValid) reference.AddClosedBrep(b, tol);
                    }
                    return reference;
                }

                if (value is Point3d)
                {
                    Point3d p = (Point3d)value;
                    if (p.IsValid) reference._points.Add(p);
                    return reference;
                }

                if (value is Point)
                {
                    Point p = (Point)value;
                    if (p.Location.IsValid) reference._points.Add(p.Location);
                    return reference;
                }

                return reference;
            }

            public bool ContainsClosed(Point3d pt, double tol, double surfaceTol)
            {
                for (int i = 0; i < _closedMeshes.Count; i++)
                {
                    if (!_closedMeshBoxes[i].Contains(pt)) continue;

                    Mesh m = _closedMeshes[i];
                    if (m.IsPointInside(pt, tol, false)) return true;

                    Point3d cp;
                    double d;
                    if (TryClosestPointOnMesh(m, pt, surfaceTol, out cp, out d) && d <= surfaceTol)
                        return true;
                }

                for (int i = 0; i < _closedBreps.Count; i++)
                {
                    if (!_closedBrepBoxes[i].Contains(pt)) continue;

                    Brep b = _closedBreps[i];
                    if (b.IsPointInside(pt, tol, false)) return true;

                    Point3d cp;
                    double d;
                    if (TryClosestPointOnBrep(b, pt, surfaceTol, out cp, out d) && d <= surfaceTol)
                        return true;
                }

                return false;
            }

            public bool IsCloseToOpen(Point3d pt, double radius)
            {
                for (int i = 0; i < _openMeshes.Count; i++)
                {
                    if (!BoxContainsInflated(_openMeshBoxes[i], pt, radius)) continue;

                    Point3d cp;
                    double d;
                    if (TryClosestPointOnMesh(_openMeshes[i], pt, radius, out cp, out d) && d <= radius)
                        return true;
                }

                for (int i = 0; i < _openBreps.Count; i++)
                {
                    if (!BoxContainsInflated(_openBrepBoxes[i], pt, radius)) continue;

                    Point3d cp;
                    double d;
                    if (TryClosestPointOnBrep(_openBreps[i], pt, radius, out cp, out d) && d <= radius)
                        return true;
                }

                for (int i = 0; i < _curves.Count; i++)
                {
                    if (!BoxContainsInflated(_curveBoxes[i], pt, radius)) continue;

                    double t;
                    if (_curves[i].ClosestPoint(pt, out t, radius))
                    {
                        if (pt.DistanceTo(_curves[i].PointAt(t)) <= radius)
                            return true;
                    }
                }

                for (int i = 0; i < _points.Count; i++)
                {
                    if (pt.DistanceTo(_points[i]) <= radius) return true;
                }

                return false;
            }

            public List<Point3d> SampleOpenGeometry(double step)
            {
                var samples = new List<Point3d>();
                step = Math.Max(step, RhinoMath.ZeroTolerance);

                foreach (Mesh m in _openMeshes)
                    SampleMesh(m, samples);

                foreach (Brep b in _openBreps)
                    SampleBrep(b, step, samples);

                foreach (Curve c in _curves)
                    SampleCurve(c, step, samples);

                samples.AddRange(_points);

                return samples;
            }

            private void AddClosedMesh(Mesh mesh, double tol)
            {
                mesh.Normals.ComputeNormals();
                mesh.Compact();
                _closedMeshes.Add(mesh);
                _closedMeshBoxes.Add(InflatedBox(mesh.GetBoundingBox(true), tol));
            }

            private void AddOpenMesh(Mesh mesh, double tol)
            {
                mesh.Normals.ComputeNormals();
                mesh.Compact();
                _openMeshes.Add(mesh);
                _openMeshBoxes.Add(InflatedBox(mesh.GetBoundingBox(true), tol));
            }

            private void AddClosedBrep(Brep brep, double tol)
            {
                try { brep.Faces.ShrinkFaces(); } catch { }
                _closedBreps.Add(brep);
                _closedBrepBoxes.Add(InflatedBox(brep.GetBoundingBox(true), tol));
            }

            private void AddOpenBrep(Brep brep, double tol)
            {
                try { brep.Faces.ShrinkFaces(); } catch { }
                _openBreps.Add(brep);
                _openBrepBoxes.Add(InflatedBox(brep.GetBoundingBox(true), tol));
            }

            private void AddCurve(Curve curve, double tol)
            {
                _curves.Add(curve);
                _curveBoxes.Add(InflatedBox(curve.GetBoundingBox(true), tol));
            }

            private static object Unwrap(object raw)
            {
                if (raw == null) return null;

                IGH_Goo goo = raw as IGH_Goo;
                if (goo != null)
                {
                    object script = goo.ScriptVariable();
                    if (script != null && !object.ReferenceEquals(script, raw))
                        return Unwrap(script);
                }

                return raw;
            }

            private static BoundingBox InflatedBox(BoundingBox bb, double tol)
            {
                if (!bb.IsValid) return bb;
                bb.Inflate(Math.Max(tol * 2.0, RhinoMath.ZeroTolerance));
                return bb;
            }

            private static bool BoxContainsInflated(BoundingBox bb, Point3d pt, double inflate)
            {
                if (!bb.IsValid || !pt.IsValid) return false;

                double pad = Math.Max(inflate, RhinoMath.ZeroTolerance);
                return pt.X >= bb.Min.X - pad && pt.X <= bb.Max.X + pad &&
                       pt.Y >= bb.Min.Y - pad && pt.Y <= bb.Max.Y + pad &&
                       pt.Z >= bb.Min.Z - pad && pt.Z <= bb.Max.Z + pad;
            }
        }

        private sealed class GridMetrics
        {
            public double MinSpacing;
            public double HalfDiagonal;
            public double BoxDiagonal;

            public static GridMetrics FromPoints(List<Point3d> points, double tol)
            {
                var result = new GridMetrics();

                double dx = MinPositiveGap(points.Select(p => p.X), tol);
                double dy = MinPositiveGap(points.Select(p => p.Y), tol);
                double dz = MinPositiveGap(points.Select(p => p.Z), tol);

                var gaps = new List<double>();
                if (dx > 0) gaps.Add(dx);
                if (dy > 0) gaps.Add(dy);
                if (dz > 0) gaps.Add(dz);

                result.MinSpacing = gaps.Count > 0 ? gaps.Min() : Math.Max(tol * 10.0, 1.0);

                double gx = dx > 0 ? dx : result.MinSpacing;
                double gy = dy > 0 ? dy : result.MinSpacing;
                double gz = dz > 0 ? dz : result.MinSpacing;
                result.HalfDiagonal = 0.5 * Math.Sqrt(gx * gx + gy * gy + gz * gz);

                BoundingBox bb = BoundingBox.Empty;
                foreach (Point3d p in points) bb.Union(p);
                result.BoxDiagonal = bb.IsValid ? bb.Diagonal.Length : result.MinSpacing;

                return result;
            }

            private static double MinPositiveGap(IEnumerable<double> values, double tol)
            {
                var list = values.ToList();
                list.Sort();

                double minGap = double.PositiveInfinity;
                double prev = double.NaN;
                bool hasPrev = false;

                foreach (double v in list)
                {
                    if (!hasPrev)
                    {
                        prev = v;
                        hasPrev = true;
                        continue;
                    }

                    double gap = Math.Abs(v - prev);
                    if (gap > tol && gap < minGap) minGap = gap;

                    if (gap > tol) prev = v;
                }

                return double.IsPositiveInfinity(minGap) ? 0.0 : minGap;
            }
        }

        private static bool TryClosestPointOnMesh(Mesh mesh, Point3d pt, double maxDistance, out Point3d closest, out double distance)
        {
            closest = Point3d.Unset;
            distance = double.PositiveInfinity;
            if (mesh == null || !mesh.IsValid) return false;

            MeshPoint mp = mesh.ClosestMeshPoint(pt, Math.Max(0.0, maxDistance));
            if (mp == null) return false;

            closest = mesh.PointAt(mp);
            if (!closest.IsValid) return false;

            distance = pt.DistanceTo(closest);
            return true;
        }

        private static bool TryClosestPointOnBrep(Brep brep, Point3d pt, double maxDistance, out Point3d closest, out double distance)
        {
            closest = Point3d.Unset;
            distance = double.PositiveInfinity;
            if (brep == null || !brep.IsValid) return false;

            ComponentIndex ci;
            double s;
            double t;
            Vector3d normal;

            if (!brep.ClosestPoint(pt, out closest, out ci, out s, out t, Math.Max(0.0, maxDistance), out normal))
                return false;

            if (!closest.IsValid) return false;

            distance = pt.DistanceTo(closest);
            return true;
        }

        private static void SampleCurve(Curve curve, double step, List<Point3d> samples)
        {
            if (curve == null || !curve.IsValid) return;

            double length = curve.GetLength();
            if (length <= RhinoMath.ZeroTolerance)
            {
                samples.Add(curve.PointAtStart);
                return;
            }

            int count = Math.Max(2, (int)Math.Ceiling(length / step) + 1);
            for (int i = 0; i < count; i++)
            {
                double d = length * i / (count - 1);
                double t;
                if (curve.LengthParameter(d, out t)) samples.Add(curve.PointAt(t));
            }
        }

        private static void SampleMesh(Mesh mesh, List<Point3d> samples)
        {
            if (mesh == null || !mesh.IsValid) return;

            foreach (Point3f v in mesh.Vertices)
                samples.Add(new Point3d(v));

            for (int i = 0; i < mesh.Faces.Count; i++)
            {
                MeshFace f = mesh.Faces[i];
                Point3d a = mesh.Vertices[f.A];
                Point3d b = mesh.Vertices[f.B];
                Point3d c = mesh.Vertices[f.C];
                if (f.IsQuad)
                {
                    Point3d d = mesh.Vertices[f.D];
                    samples.Add((a + b + c + d) / 4.0);
                }
                else
                {
                    samples.Add((a + b + c) / 3.0);
                }
            }
        }

        private static void SampleBrep(Brep brep, double step, List<Point3d> samples)
        {
            if (brep == null || !brep.IsValid) return;

            foreach (BrepFace face in brep.Faces)
            {
                if (face == null) continue;

                Interval u = face.Domain(0);
                Interval v = face.Domain(1);
                int uCount = EstimateFaceSampleCount(face, 0, step);
                int vCount = EstimateFaceSampleCount(face, 1, step);

                for (int i = 0; i < uCount; i++)
                {
                    double uu = u.ParameterAt(uCount == 1 ? 0.5 : (double)i / (uCount - 1));
                    for (int j = 0; j < vCount; j++)
                    {
                        double vv = v.ParameterAt(vCount == 1 ? 0.5 : (double)j / (vCount - 1));
                        Point3d p = face.PointAt(uu, vv);
                        if (!p.IsValid) continue;

                        if (face.IsPointOnFace(uu, vv) != PointFaceRelation.Exterior)
                            samples.Add(p);
                    }
                }
            }
        }

        private static int EstimateFaceSampleCount(BrepFace face, int direction, double step)
        {
            try
            {
                Interval a = face.Domain(direction);
                Interval b = face.Domain(1 - direction);
                double bMid = 0.5 * (b.T0 + b.T1);

                Curve iso = direction == 0
                    ? face.IsoCurve(0, bMid)
                    : face.IsoCurve(1, bMid);

                double len = iso != null ? iso.GetLength() : step;
                return Math.Max(2, Math.Min(200, (int)Math.Ceiling(len / step) + 1));
            }
            catch
            {
                return 3;
            }
        }
    }
}
