using System;

namespace WASPer.LiveLink
{
    /// <summary>
    /// CRC-32/ISO-HDLC, reflected polynomial 0xEDB88320, init 0xFFFFFFFF,
    /// final XOR 0xFFFFFFFF. Identical to zlib.crc32 and to
    /// System.IO.Hashing.Crc32, which matters because the golden frame fixture
    /// is generated by an independent Python implementation.
    /// </summary>
    /// <remarks>
    /// Implemented inline rather than taken from the System.IO.Hashing package so
    /// this assembly ships as a single dependency-free DLL. A table-based CRC32
    /// clears roughly 1 GB/s, which is well inside the 1 ms budget at a 2 MB frame.
    /// </remarks>
    public static class WasperLiveLinkCrc32
    {
        private static readonly uint[] Table = BuildTable();

        private static uint[] BuildTable()
        {
            var table = new uint[256];
            for (uint i = 0; i < 256; i++)
            {
                uint c = i;
                for (int k = 0; k < 8; k++)
                    c = (c & 1) != 0 ? 0xEDB88320u ^ (c >> 1) : c >> 1;
                table[i] = c;
            }
            return table;
        }

        public static uint Compute(byte[] buffer, int offset, int count)
        {
            if (buffer == null) throw new ArgumentNullException(nameof(buffer));
            if (offset < 0 || count < 0 || offset + count > buffer.Length)
                throw new ArgumentOutOfRangeException(nameof(count));

            uint crc = 0xFFFFFFFFu;
            uint[] table = Table;
            int end = offset + count;
            for (int i = offset; i < end; i++)
                crc = table[(crc ^ buffer[i]) & 0xFF] ^ (crc >> 8);

            return crc ^ 0xFFFFFFFFu;
        }
    }
}
